### ISSUE TITLE
RuntimeError when changing a "criteria requirement"

### ISSUE THREAD

**Issue by kwoot** [LibrePlan/libreplan#1784]
(Original Bugzilla Bug ID: [1640](http://bugs.libreplan.org/show_bug.cgi?id=1640))

Date: 2014-02-12 14:11:40
From: Tobias Schmitt \<<tob0801@freenet.de>\>
To: Javier Morán \<<jmoran@igalia.com>\>
Version: libreplan-1.2 (1.2.x)
Last updated: 2014-02-13 15:55:48

---
(Note: this issue was migrated automatically with [bugzilla2github.py tool](https://github.com/LibrePlan/bugzilla2github) )

**Comment by kwoot** [comment]
Can not reproduce on 1.4.1. Most likely fixed.

**Comment by f4y** [comment]
Hello, same problem with 1.4.1. How i can fix it ? Ty

**Comment by kwoot** [comment]
Well, you can git clone the repo, checkout branch libreplan-1.4 and start debugging.
Hope this helps.

**Comment by f4y** [comment]
Hello, ty for the fast reply. Unfortunately, I haven't the skills to debug it. I just wanted to figure out if I had done something wrong or it is actually a known bug. Ty

**Comment by kwoot** [comment]
ok.
