### ISSUE TITLE
Hibernate LazyInitialization error for users with read & write permissions on single projects

### ISSUE THREAD

**Issue by kwoot** [LibrePlan/libreplan#1837]
(Original Bugzilla Bug ID: [1693](http://bugs.libreplan.org/show_bug.cgi?id=1693))

Date: 2016-05-26 08:32:36
From: Daniele Gagliardi \<<dnl.gagliardi@gmail.com>\>
To: Jeroen Baten \<<jeroen@libreplan.com>\>
Version: libreplan-1.4 (1.4.x)
Last updated: 2016-05-26 08:36:48

---
(Note: this issue was migrated automatically with [bugzilla2github.py tool](https://github.com/LibrePlan/bugzilla2github) )

**Comment by vmazurashu** [comment]
Can't reproduce.
Branch libreplan-1.4

**Comment by kwoot** [comment]
If you can't reproduce it doesn't exist :-)
