### ISSUE TITLE
Cannot install libreplan on ubuntu 16.04 server

### ISSUE THREAD

**Issue by kwoot** [LibrePlan/libreplan#1841]
(Original Bugzilla Bug ID: [1697](http://bugs.libreplan.org/show_bug.cgi?id=1697))

Date: 2016-08-23 18:43:57
From: Uwe Witfer \<<uwe.witfer@gmx.de>\>
To: Jeroen Baten \<<jeroen@libreplan.com>\>
Version: libreplan-1.4 (1.4.x)
Last updated: 2016-08-23 19:44:55

---
(Note: this issue was migrated automatically with [bugzilla2github.py tool](https://github.com/LibrePlan/bugzilla2github) )

**Comment by tramseyer** [comment]
Got it working on both Ubuntu 18.04 and 20.04 by adding some additional steps to the original guide:

Set default JDK:
`update-java-alternatives -s java-1.8.0-openjdk-amd64`

Add missing dependency to the end of libreplan/libreplan-webapp/pom.xml:
```
        <dependency>
            <groupId>org.olap4j</groupId>
            <artifactId>olap4j</artifactId>
            <version>1.2.0</version>
        </dependency>
```

Compile project but skip tests:
`mvn -DskipTests clean install`
