### ISSUE TITLE
Cannot edit TimeSheet Lines, receive InvocationTargetException instead

### ISSUE THREAD

**Issue by kwoot** [LibrePlan/libreplan#1846]
(Original Bugzilla Bug ID: [1702](http://bugs.libreplan.org/show_bug.cgi?id=1702))

Date: 2016-12-18 21:03:07
From: Leslie Mann \<<lmann@linuxolutions.com>\>
To: Jeroen Baten \<<jeroen@libreplan.com>\>
Version: master (1.4.x)
Last updated: 2016-12-29 00:40:26

---
(Note: this issue was migrated automatically with [bugzilla2github.py tool](https://github.com/LibrePlan/bugzilla2github) )

**Comment by vmazurashu** [comment]
Can't reproduce anymore! Can someone confirm the same?

**Comment by kwoot** [comment]
So you think we can close this isse?

**Comment by vmazurashu** [comment]
Yes, sure we can close it
