### ISSUE TITLE
Fix mess in  libreplan/libreplan-business/src/main/resources/db.changelog-1.4.xml

### ISSUE THREAD

**Issue by kwoot** [LibrePlan/libreplan#1868]
A developer has changed a database changeset in this file in the past.

This causes an error because of changed/unexpected hash in database table databasechangelog, field md5sum because it is managed by hibernate.

To fix this: reset file to 1.4.1 release, look at all the changes and move them to a new changeset on top of the prior one.

**Comment by penguineer** [comment]
Is this related to #1855 ?

**Comment by kwoot** [comment]
Yes it is. Thanks for the heads up.

**Comment by kwoot** [comment]
Fixed
