### ISSUE TITLE
[Question] Ubuntu 14 LTS expiration date

### ISSUE THREAD

**Issue by dmarconi** [LibrePlan/libreplan#1876]
I'm currently evaluating the usage of libreplan for the company I work for

Long Term Support for Ubuntu 14 will end in April 2019. Are there any plans so far to move Libreplan to a more recent distribution?

Thanks in advance!!!

 Daniele

**Comment by kwoot** [comment]
Of course there are! And the more companies support LibrePlan financially the earlier it will be done.

**Comment by tramseyer** [comment]
Got it working on both Ubuntu 18.04 and 20.04 by adding some additional steps to the original guide:

Set default JDK:
`update-java-alternatives -s java-1.8.0-openjdk-amd64`

Add missing dependency to the end of libreplan/libreplan-webapp/pom.xml:
```
        <dependency>
            <groupId>org.olap4j</groupId>
            <artifactId>olap4j</artifactId>
            <version>1.2.0</version>
        </dependency>
```

Compile project but skip tests:
`mvn -DskipTests clean install`
