### ISSUE TITLE
Maven compile error no access to org.zkoss.lang.ClassResolver

### ISSUE THREAD

**Issue by birkhoms** [LibrePlan/libreplan#1883]
Hi there,

the last two days I tried to setup a Debian based LibrePlan server. I know that you only support Ubuntu 14.x, and sadly I have failed there too. Anyway, during "mvn clean install" I receive the follwoing error :

[ERROR] /home/libreplan/ganttzk/src/main/java/org/zkoss/ganttz/util/MenuBuilder.java:[101,33] cannot access org.zkoss.lang.ClassResolver
  class file for org.zkoss.lang.ClassResolver not found
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] LibrePlan .......................................... SUCCESS [  0.547 s]
[INFO] LibrePlan Business Module .......................... SUCCESS [01:05 min]
[INFO] LibrePlan ZK Components Module ..................... FAILURE [  1.570 s]
[INFO] LibrePlan Web Client Module ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:07 min
[INFO] Finished at: 2018-09-07T13:28:11+00:00
[INFO] Final Memory: 38M/128M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project ganttzk: Compilation failure
[ERROR] /home/libreplan/ganttzk/src/main/java/org/zkoss/ganttz/util/MenuBuilder.java:[101,33] cannot access org.zkoss.lang.ClassResolver
[ERROR] class file for org.zkoss.lang.ClassResolver not found
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ganttzk

I tried to add the dependency to the pom file, however then it is pointing to missing source files in the nexus repository. Since I am quite new to java and web builders in general, can you please give a some advice how I can solve this. Thank you very much. 

Yours,
Markus

**Comment by grypho** [comment]
The error is caused by using openjdk-10-jdk as the standard JAVA interpreter (which is caused by installing the package default-jre-headless). Compilation only works for openjdk-8-jdk. 

If you are using that machine only for libreplan compilation (i.e. VirtualBox machine) you can safely uninstall all the openjdk-10 stuff.

Carsten
