### ISSUE TITLE
relocate maven artifacts to new nexus server

### ISSUE THREAD

**Issue by kwoot** [LibrePlan/libreplan#1904]
The nexus.libreplan.org server has been down for several weeks now. It is unclear when this will be fixed. So we are going to setup a new nexus server at nexus.libreplan.dev.

**Comment by kwoot** [comment]
Server nexus.libeplan.dev has been setup.
pom.xml has been changed. 
Commit  #91f2e3

**Comment by kwoot** [comment]
Done.

**Comment by grypho** [comment]
When trying to access nexus.libreplan.dev I get an _503 Service Unavailable_ error. Could you please check that the server is up and running?

**Comment by kwoot** [comment]
Restarted. Weird. Decided to shutdown at 0:04 this morning. I will monitor this for the next days.

**Comment by grypho** [comment]
Thanks! Seems to be up again. But still I cannot build using the most recent GIT version:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for LibrePlan 1.6.0:
[INFO]
[INFO] LibrePlan .......................................... SUCCESS [  0.315 s]
[INFO] LibrePlan Business Module .......................... SUCCESS [  0.015 s]
[INFO] LibrePlan ZK Components Module ..................... SUCCESS [  0.010 s]
[INFO] LibrePlan Web Client Module ........................ FAILURE [ 29.612 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.452 s
[INFO] Finished at: 2019-07-01T08:21:48Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project libreplan-webapp: Could not resolve dependencies for project org.libreplan:libreplan-webapp:war:1.6.0: The following artifacts could not be resolved: org.libreplan:ganttzk:jar:1.6.0, org.libreplan:libreplan-business:jar:1.6.0: Could not find artifact org.libreplan:ganttzk:jar:1.6.0 in thirdparty (https://nexus.libreplan.dev/repository/thirdparty-libreplan16/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :libreplan-webapp

```

Looks to me that an artifact is not found on nexus.libreplan.dev. But I do not have enough experience to trace that issue down.

**Comment by kwoot** [comment]
The build error message seems to make no sense. Will look into it later.

**Comment by grypho** [comment]
My fault. I had an issue with the postgresql database which is used during compilation. Seems to work now and I can continue to resolve dependency issues. Seems like I have to add several dependencies in the pom.xml files on my machine. 

Thanks for your help!

**Comment by kwoot** [comment]
"Seems like I have to add several dependencies in the pom.xml files on my machine.". Nope. it should run as is. But an old database can cause troubles. Please open a new ticket if you have troubles. This ticket was about relocating the nexus server :-).
