### ISSUE TITLE
org.zkoss.ganttz.util.LongOperationFeedback  in Gantt view

### ISSUE THREAD

**Issue by grypho** [LibrePlan/libreplan#1908]
When entering a project gantt view, my browser (Firefox, Chrome) blocks and issues a "site not responding" warning. On the server side, I get a org.zkoss.ganttz.util.LongOperationFeedback error in my tomcat logs. Looks like Issue #1808 which was closed because of missing feedback.

```
ERROR [03-Juli 07:40:52] [pool-4-thread-2] org.zkoss.ganttz.util.LongOperationFeedback  - unable to access desktop
org.zkoss.zk.ui.DesktopUnavailableException: Stopped
        at org.zkoss.zk.ui.impl.PollingServerPush.activate(PollingServerPush.java:315)
        at org.zkoss.zk.ui.impl.DesktopImpl.activateServerPush(DesktopImpl.java:1629)
        at org.zkoss.zk.ui.Executions.activate(Executions.java:1002)
        at org.zkoss.zk.ui.Executions.activate(Executions.java:973)
        at org.zkoss.ganttz.util.LongOperationFeedback$NotBlockingDesktopUpdates.run(LongOperationFeedback.java:264)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
ERROR [03-Juli 07:40:52] [pool-4-thread-1] org.zkoss.ganttz.util.LongOperationFeedback  - error executing background operation
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.zkoss.zk.ui.DesktopUnavailableException: Stopped
        at org.zkoss.ganttz.util.LongOperationFeedback$4.waitUntilShowingAllUpdates(LongOperationFeedback.java:215)
        at org.zkoss.ganttz.util.LongOperationFeedback$4.doOperation(LongOperationFeedback.java:207)
        at org.zkoss.ganttz.util.LongOperationFeedback.lambda$progressive$3(LongOperationFeedback.java:181)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.zkoss.zk.ui.DesktopUnavailableException: Stopped
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.zkoss.ganttz.util.LongOperationFeedback$4.waitUntilShowingAllUpdates(LongOperationFeedback.java:213)
        ... 5 more
Caused by: java.lang.RuntimeException: org.zkoss.zk.ui.DesktopUnavailableException: Stopped
        at org.zkoss.ganttz.util.LongOperationFeedback$NotBlockingDesktopUpdates.run(LongOperationFeedback.java:267)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
Caused by: org.zkoss.zk.ui.DesktopUnavailableException: Stopped
        at org.zkoss.zk.ui.impl.PollingServerPush.activate(PollingServerPush.java:315)
        at org.zkoss.zk.ui.impl.DesktopImpl.activateServerPush(DesktopImpl.java:1629)
        at org.zkoss.zk.ui.Executions.activate(Executions.java:1002)
        at org.zkoss.zk.ui.Executions.activate(Executions.java:973)
        at org.zkoss.ganttz.util.LongOperationFeedback$NotBlockingDesktopUpdates.run(LongOperationFeedback.java:264)
        ... 5 more

```

I'm using the most recent git version (mysql,prod), a tomcat 8 server and openjdk version 1.8.0_212. Any Idea what is going wrong?

If it is helpful, I can provide a database dump as there is no production relevant data inside. So far I've only created four resources, one project and within the project one.

**Comment by grypho** [comment]
Additional information: Before the error message I can find an addition error message in my log files. Im not sure, if that message is related to the issue.

`ERROR [03-Juli 08:02:30] [http-nio-8080-exec-9] org.libreplan.web.error.PageForErrorOnEvent  - /libreplan/planner/__history__.html [Status Code: 404]`

**Comment by grypho** [comment]
Update:
Tweaked webserver to serve an empty __history__.html -- No change in behaviour.

Also set log4j level to TRACE. No errors beside LongOperationFeedback, no warnings at in roughly 150MB log data.

Actually instrumenting LongOperationFeedback.java to get a clue why notBlockingDesktopUpdates does not finish.

**Comment by grypho** [comment]
Another update:
1. LongOperationFeedback.java instrumentation was not that successful (maybe because I lack Java knowledge). 

2. It looks like an initial update of the gantt-diagram succeeds (at least the project times are drawn) and the browser hangs afterwards (1 Core with full load).

3. I managed to break when the browser was at full load (took me only ~10 tries). See the attached screenshot. Most interesting should be the call stack
![libreplan-crash1](https://user-images.githubusercontent.com/9314376/60591410-b3e47c00-9d9e-11e9-8bd4-d69b98987bc6.png)


I managed to get

**Comment by grypho** [comment]
I placed some debugging statements within the code of timeplotz-1.1_50.jar. So far it looks like the JavaScript function _calculateGrid is called several times when the view is being built. The first dozen of calls the function terminates immidiately because this._canvas is null. So far, everything is fine.

Then this._canvas gets a value and the function is called again. The function call and the variable values look like this: 
![libreplan-crash2](https://user-images.githubusercontent.com/9314376/60644905-a3341480-9e37-11e9-8e41-82231a2eb226.png)

The first part (with the variable d being incremented/decremented) calculates the magnitude that is being displayed. Then there is a loop `while(true)...` which increments a (by step e) until the **projected value** reaches this._gridSpacing (in my case 50). There the mess begins with the function this.toScreen().

![libreplan-crash3](https://user-images.githubusercontent.com/9314376/60645214-66b4e880-9e38-11e9-8388-7c9c4aba1d3d.png)

In the function .toScreen(b) the value b is projected to the canvas. 

Modern browsers use a iterative rendering process where elements have a default size of 0 when they are initialized. The height is being increased as there is content added.

This results in a projection to 0 in every case since the result is multiplied with the height. In the calling function this behavior results in an infinite loop which crashes the browser. 

To my mind this is an error within the timeplotz component. The LongperationFeedback is only a result because Tomcat cannot push any more data to the browser (which hangs in an infinite loop).

As the last update of timeplotz in the maven repository is from 2012 i doubt there won't be an official bug fix for that issue. First I will try to hack that issue and see if it solves the problem. If so, we have to discuss how that issue can be solved in a clean way.

**Comment by kwoot** [comment]
I agree. Please use postgresql as database as that is the main development focus. If you want a database dump I can provide several. Just send me an email.

**Comment by grypho** [comment]
The height issue has been confirmed as the source of all the mess. 
I changed in
timeplotz.jar/web/js/timeplotz/ext/timeplot/scripts/geometry.js
```

[...]
_calculateGrid:function(){
  var c=[];
  if(!this._canvas||this._valueRange==0){return c}
[...]
```
into
```
[...]
_calculateGrid:function(){
  var c=[];
  if(!this._canvas||this._canvas.height==0||this._valueRange==0){return c}
[...]
```

and the timeplot works fine now without any crashes in the frontend or backend.

Any Idea how that can be implemented in a clean way?

**Comment by kwoot** [comment]
Seems clean enough to me. Good work!

**Comment by kwoot** [comment]
Oh wait, best to close with a PR and a commit :-). Sorry for my enthusiasm.

**Comment by grypho** [comment]
Any Idea how that can be implemented in a clean way?

The file that needs to be patched is being fetched by maven as a dependency. Can such a patch (of a jar file) be implemented in maven in some way?

**Comment by kwoot** [comment]
I doubt it.

**Comment by kwoot** [comment]
Maybe @ymauray knows something?

**Comment by kwoot** [comment]
What we can do is fork the jar, patch the file and upload to our own nexus server. I know it's dirty but for the time being maybe the only solution given the age of those libs.

**Comment by kwoot** [comment]
Could you email me a patched jar I can upload to our nexus server?

**Comment by grypho** [comment]
Hi Jeroen,

i'm currently on vacation with quite bad Internet access. I'll try to patch that file this evening but first I have to set up a VM with Ubuntu 14.4. 

Carsten 

Am 17. Juli 2019 11:05:01 MESZ schrieb Jeroen Baten <notifications@github.com>:
>Could you email me a patched jar I can upload to our nexus server?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LibrePlan/libreplan/issues/1908#issuecomment-512169373

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ymauray** [comment]
It's vacation time for the whole team except for the boss 😜

I myself can't do anything until the evening of the 26th. 

TTY then !

Envoyé de mon iPhone

**Comment by kwoot** [comment]
Hi @grypho (and @ymauray ). Vacation comes first! Always.
I will be on holiday most of august.
This can wait. Really.
(But I really love the enthusiasm!)

**Comment by ymauray** [comment]
Coder.is a 24/7 passion 😎 except I can spawn a VM while sitting next to the pool overseeing my daughter spashing water on her grandmother. Not sorry 😁

Envoyé de mon iPhone

**Comment by kwoot** [comment]
@ymauray: LOL. 
@grypho: you need 14.04 to build it? Please tell me some day why. I like to learn.

**Comment by grypho** [comment]
Ok, 16.04. But still a quite old distro. I'd like to build it with a more recent distro, i.e. Debian 10 or Ubuntu 19.

**Comment by grypho** [comment]
To solve this issue, replace the timeplotz-xxx.jar in the libreplan-webapp/target/libreplan-webapp/WEB-INF/lib directory with [this one](https://carsten.familie-schumann.info/libreplan-patches/timeplotz-1.1_50.jar)

**Comment by kwoot** [comment]
Great! Thanks. I would prefer to focus on Ubuntu LTS. There also lies the focus of our clients.

**Comment by kwoot** [comment]
Uploaded. Renamed to 1.1.50a. Path is here:
https://nexus.libreplan.dev/repository/thirdparty-libreplan16/dev/libreplan/zkoss/timeplotz/1.1_50a/timeplotz-1.1_50a.1_50a.jar

**Comment by kwoot** [comment]
Uploaded: https://nexus.libreplan.dev/repository/thirdparty-libreplan16/dev/libreplan/zkoss/timeplotz/1.1_50a/timeplotz-1.1_50a.1_50a.jar

**Comment by grypho** [comment]
@kwoot Do we need to update one of the dependency files or is that new files automatically fetched insted of the old one?

**Comment by grypho** [comment]
Issue is fixed.
