### ISSUE TITLE
website ssl expired libreplan.dev

### ISSUE THREAD

**Issue by mohamedhagag** [LibrePlan/libreplan#1920]
LE website ssl expired for https://libreplan.dev

**Comment by kwoot** [comment]
Thanks! Will be back on Tuesday and fix. 

⁣TypeApp voor Android downloaden ​

Op 12 okt. 2019 01:16, om 01:16, "Mohamed M. Hagag" <notifications@github.com> schreef:

**Comment by kwoot** [comment]
Fixed. (for now)
