### ISSUE TITLE
Horizontal shift between Gantt and Resource view

### ISSUE THREAD

**Issue by grypho** [LibrePlan/libreplan#1922]
In project planning mode, the Resource allocation view (bottom) is shifted left in relation to the Gantt view. See attached Screenshot.
![grafik](https://user-images.githubusercontent.com/9314376/66900995-18e67980-effe-11e9-98f7-f87a3b5b4f75.png)

**Comment by kwoot** [comment]
Damn! I hadn't realised this before. It happens because the T/M column has been added I guess. Hm, shouldn't be too hard to fix I hope.

**Comment by grypho** [comment]
Fixed with pull request #1923
