### ISSUE TITLE
Website down? 

### ISSUE THREAD

**Issue by edent** [LibrePlan/libreplan#1924]
I'm unable to reach the websites listed in the readme. 

https://downforeveryoneorjustme.com/bugs.libreplan.org

https://downforeveryoneorjustme.com/libreplan.org

**Comment by grypho** [comment]
Hi @edent,

please use the issue tracker of GitHub for bug reports. There is an certificate issue for libreplan.dev that prevents you from accessing the site in your browser. I'm sure, @kwoot is already working on it.

**Comment by edent** [comment]
I didn't know about the .dev site. I'm talking about all the references in the code to the .org site.

* https://github.com/LibrePlan/libreplan/blob/master/README.rst#webpage
* https://github.com/LibrePlan/libreplan/blob/master/libreplan-business/src/main/java/org/libreplan/business/common/VersionInformation.java#L48
* https://github.com/LibrePlan/libreplan/blob/master/doc/src/technical/howto-install-libreplan-from-deb.txt#L8
* https://github.com/LibrePlan/libreplan/blob/master/doc/src/technical/howto-install-libreplan.txt#L24
* https://github.com/LibrePlan/libreplan/blob/master/debian/libreplan.postinst#L123

and several more.

**Comment by grypho** [comment]
Terence, 
I know that you are talking of the .org site. The site changed some months to .dev. 
See commit https://github.com/LibrePlan/libreplan/commit/91f2e3df258c237acef319b56ba5a02ae7a9162a

There are several references in the text documents that still point to the old site (and have to be fixed).

**Comment by kwoot** [comment]
Please ignore the references to .org. Use .dev instead.  I know this needs to be fixed.

**Comment by kwoot** [comment]
Changed the mentions in the wiki.

**Comment by kwoot** [comment]
Changed all references to libreplan.org to libreplan.dev. See 06673d22b95ca7a7dfc080588c8fce03e4f79316
