### ISSUE TITLE
"HTTP Status 404 – Not Found" on debian

### ISSUE THREAD

**Issue by D3faIt** [LibrePlan/libreplan#1926]
### Specs

- OS: Debian GNU/Linux bullseye/sid
- Kernel: 5.3.0-2-amd64 GNU/Linux

---

Hi.

I tried installing Libreplan with the .deb package, but it failed because it couldn't find tomcat6 (I know tomcat8 is the current used one, but Libreplan still failed to install)

I decided to install it the manual way.

[I followed the instructions](https://github.com/LibrePlan/libreplan/wiki/LibrePlan-installation#debianubuntu) and went through all commands.

After restarting tomcat8 and going to http://localhost:8080/libreplan/ it displayed a 404 not found page:

![Screenshot_20191124_065717](https://user-images.githubusercontent.com/8147434/69490413-bd729b80-0e87-11ea-8600-8d4e42865c8f.png)

I have no experience with Tomcat before and has never used PostgreSQL before.

Does anyone know what the issue might be?

**Comment by besil** [comment]
same problem here

**Comment by kwoot** [comment]
Please compile the master branch and run it using the Jetty webserver. That currently works.
