### ISSUE TITLE
Ubuntu 22.04 LTS - installation problem unmet dependencies.

### ISSUE THREAD

**Issue by Special-Niewbie** [LibrePlan/libreplan#1952]
Hi everyone, I was trying this great program through the Demo site. 

I would like to try it directly on my personal Linux computer, but the latest version of Libreplan `1.4.1-1.deb `does not want to install with the error "unmet dependencies". 
Do you have any idea how can I unblock this situation?

**Comment by kwoot** [comment]
The 1.4.1 release is back from 2014-ish. It is for Ubuntu 14.04. There have not been packages since. You can build directly from the current source. 
There will be packages created in the near future.
